### ISSUE TITLE
Project structure and tests

### ISSUE THREAD

**Issue by maZahaca** [findexchange/data-group-service#4]
You have comments like this:

```
curl -i -H "Content-Type: application/json"  -X POST http://127.0.0.1:5000/app/v1.0/upload -d @sample_input.json
```

We need to have following improvements
- Create such structure (folders) of the project
  - ./src -> for source codes
  - ./test -> tests of the code
  - Move "app.py" and "data_sort.py" to the "src" folder.
  - Move "sample_input.json" to "test" folder
- Create a test class which covers flask API (in the test folder) [Read more about flask tests](http://flask.pocoo.org/docs/0.11/testing/)
  - it should send as input data from sample_input.json
  - it should check results from the API (number of rows, their counts, ids and etc.) - to be sure, that it's right.

**Comment by XiaoPa** [comment]
just committed new updated codes, please review and leave comments

**Comment by maZahaca** [comment]
You can close it, if it's fine
